version: '3.8'

services:

#  zookeeper:
#    image: wurstmeister/zookeeper
#    ports:
#      - "2181:2181"
#
#  kafka:
#    image: wurstmeister/kafka:2.13-2.8.1
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: host.docker.internal
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock

  # http server + kafka publisher
  service1:
    image: service1:1.0
    ports:
      - "8081:8081"

#  # kafka listener + kafka publisher
#  service2:
#    image: service2:1.0
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#
#  # kafka listener + database writer
#  service3:
#    image: service3:1.0
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
