version: '3.1'

services:
  mongo:
    image: mongo:5.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "mn123456"
    ports:
      - "27017:27017"
    container_name: mn_0
    volumes:
      - ../.data/mng5:/data/db
